name: Release workflow

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build project
        run: |
          cd /home/runner/work/looztick/
          rm -r looztick/.git*
          tar -zcvf looztick-${{ github.ref_name }}.tgz looztick

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: looztick-${{ github.ref_name }}.tgz
          path: /home/runner/work/looztick/looztick-${{ github.ref_name }}.tgz
      
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/work/looztick/looztick-${{ github.ref_name }}.tgz
          body: "New release is available"
          name: ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
